### ISSUE TITLE
Please add a snapshot 

### ISSUE THREAD

**Issue by maoruibin** [SumiMakito/AdvancedTextSwitcher#1]
you make AdvancedTextSwitcher, and it is a view ,so if show a pic on readme file ,the reader will understand you AdvancedTextSwitcher easily

**Comment by sumimakito** [comment]
This library contains animation effects, so the best way to show how it works is to watch a video. I've added a snapshot in previous commit. And if you're able to watch YouTube, I recommend you to watch the video instead. Thanks for opened this issue. :)

**Comment by maoruibin** [comment]
OK
